version: '3'

services:
  postgres:
    image: postgres
    container_name: pgsql-dev
    networks: 
      - redarc
    environment:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    volumes:
      - pgredarc01:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redarc:
    build:
      context: "{{ base_dir }}/{{ domain }}/clone"
      dockerfile: Dockerfile
    image: redarc
    container_name: redarc
    networks:
      - redarc
    environment:
      REDARC_API: https://redarc.{{ domain }}/api
      SERVER_NAME: redarc.{{ domain }}
      PGPASSWORD: "{{ postgres_password }}"
      ES_ENABLED: 'true'
      ES_HOST: https://es.{{ domain }}
      ES_PASSWORD: "{{ es_password }}"
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: es01
    networks:
      - redarc
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD={{ es_password }}"
      - "http.host=https://es.{{ domain }}"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - esredarc01:/usr/share/elasticsearch/data

networks:
  redarc:
    driver: bridge

volumes:
  pgredarc01:
    driver: local
  esredarc01:
    driver: local

